import logging

from django.db.models.signals import post_save, pre_save

from core.models import Link
from core.services.links import (
    generate_shortened_hash,
    get_name_from_url,
    sanitize_link,
)

logger = logging.getLogger(__name__)


def trigger_generate_shortened_hash(
    sender, instance, created, **kwargs
):  # pylint: disable=unused-argument
    operation = 'CREATED' if created else 'UPDATED'
    logger.info(f'{operation}: Link slug="{instance.slug}"')
    instance.sanitized_link = sanitize_link(instance.original_link)
    instance.shortened_hash = generate_shortened_hash(uid=instance.id)
    _save_avoiding_infinite_post_save_signal_loop(instance)


def trigger_set_name_from_url_if_name_empty(
    sender, instance, **kwargs
):  # pylint: disable=unused-argument
    if not instance.name:
        logger.info(
            f'Empty name for link="{instance.original_link}", autogenerating...'
        )
        instance.name = get_name_from_url(instance.original_link)
        logger.info(f'Autogenerated name for link="{instance.original_link}".')


URL_POST_SAVE_PARAMS = {
    'receiver': trigger_generate_shortened_hash,
    'sender': Link,
    'dispatch_uid': 'trigger_generate_shortened_hash',
}

URL_PRE_SAVE_PARAMS = {
    'receiver': trigger_set_name_from_url_if_name_empty,
    'sender': Link,
    'dispatch_uid': 'trigger_set_name_from_url_if_name_empty',
}


def _save_avoiding_infinite_post_save_signal_loop(instance):
    post_save.disconnect(**URL_POST_SAVE_PARAMS)
    instance.save()
    post_save.connect(**URL_POST_SAVE_PARAMS)


post_save.connect(**URL_POST_SAVE_PARAMS)
pre_save.connect(**URL_PRE_SAVE_PARAMS)
