# Generated by Django 3.1.1 on 2020-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='url', name='shortened_url'),
        migrations.AddField(
            model_name='url',
            name='shortened_hash',
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True
            ),
        ),
    ]
