# Generated by Django 3.1.1 on 2020-10-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='shortened_url',
            field=models.URLField(blank=True, null=True, unique=True),
        )
    ]
