# Generated by Django 3.1.1 on 2020-11-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201115_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='sanitized_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
